name: bootcamp CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint the code base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: flake8
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: install dependencies
      run: python -m pip install --upgrade pip
    - name: lint
      run: |
        pip install -q flake8
        flake8

  build-and-test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2.2.0
      with:        
        auto-update-conda: true
        python-version: 3.11
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda create -n test-bootcamp
        conda activate test-bootcamp
        pip install pytest
    - name: Tests
      shell: bash -l {0}
      run: |
        conda activate test-bootcamp
        pytest
